version: "3.9"

services:
  postgres-test:
    image: postgres:15-alpine
    container_name: backend_postgres_test
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: app_test
    ports:
      - "5432:5432"
